primary_model: "anthropic_general_budget"

model_overrides:
  temperature: 0.2
  max_tokens: 600
  
  # Task-specific overrides
  per_model:
    skill_analysis:
      temperature: 0.1
      max_tokens: 300
      
    priority_calculation:
      temperature: 0.2
      max_tokens: 200
      
    agent_selection:
      temperature: 0.3
      max_tokens: 400
      
    wellbeing_assessment:
      temperature: 0.4
      max_tokens: 500