primary_model: "llm_fast_premium"

model_overrides:
  temperature: 0.2
  max_tokens: 800
  
  # Task-specific overrides
  per_model:
    skill_analysis:
      temperature: 0.1
      max_tokens: 400
      
    priority_calculation:
      temperature: 0.2
      max_tokens: 300
      
    agent_selection:
      temperature: 0.3
      max_tokens: 500
      
    wellbeing_assessment:
      temperature: 0.4
      max_tokens: 600