primary_model: "claude-3-sonnet"

model_preferences:
  evaluation_tasks:
    primary: "claude-3-sonnet"
    fallback: ["gpt-4", "claude-3-haiku"]
    
  complex_evaluation:
    primary: "gpt-4"
    fallback: ["claude-3-sonnet", "mistral-7b"]
    
  quick_evaluation:
    primary: "claude-3-haiku"
    fallback: ["gpt-3.5-turbo", "mistral-7b"]

model_overrides:
  temperature: 0.3
  max_tokens: 1500
  
  per_model:
    claude-3-sonnet:
      temperature: 0.2
      max_tokens: 2000
      
    gpt-4:
      temperature: 0.1
      max_tokens: 1800