primary_model: "anthropic_reasoning_premium"

model_preferences:
  evaluation_tasks:
    primary: "anthropic_reasoning_premium"
    fallback: ["openai_general_standard", "anthropic_general_budget"]
    
  complex_evaluation:
    primary: "openai_general_standard"
    fallback: ["anthropic_general_standard", "local_general_budget"]
    
  quick_evaluation:
    primary: "anthropic_general_budget"
    fallback: ["openai_general_budget", "local_general_budget"]

model_overrides:
  temperature: 0.3
  max_tokens: 1500
  
  per_model:
    claude-4-sonnet:
      temperature: 0.2
      max_tokens: 2000
      
    gpt-4:
      temperature: 0.1
      max_tokens: 1800