primary_model: "llm_fast_premium"

model_preferences:
  evaluation_tasks:
    primary: "llm_general_premium"
    fallback: ["llm_fast_premium", "llm_fast_budget"]
    
  complex_evaluation:
    primary: "llm_general_premium"
    fallback: ["llm_fast_premium", "llm_fast_budget"]
    
  quick_evaluation:
    primary: "llm_fast_premium"
    fallback: ["llm_fast_budget", "llm_general_premium"]

model_overrides:
  temperature: 0.3
  max_tokens: 1500
  
  per_model:
    claude-4-sonnet:
      temperature: 0.2
      max_tokens: 2000
      
    gpt-4:
      temperature: 0.1
      max_tokens: 1800