primary_model: "anthropic_general_budget"

model_overrides:
  temperature: 0.3          # Lower temperature for consistent quality assessment
  max_tokens: 1000          # Sufficient for quality analysis
  
  # Task-specific overrides
  per_model:
    quality_assessment:
      temperature: 0.2      # Very low for objective assessment
      max_tokens: 500
      
    response_adjustment:
      temperature: 0.5      # Slightly higher for creative improvement
      max_tokens: 800
      
    context_analysis:
      temperature: 0.3
      max_tokens: 300