primary_model: "deepinfra_general_standard"

model_overrides:
  temperature: 0.2          # Low temperature for consistent sentiment analysis
  max_tokens: 800           # Sufficient for frustration analysis
  
  # Task-specific overrides
  per_model:
    frustration_analysis:
      temperature: 0.1      # Very low for objective sentiment analysis
      max_tokens: 500
      
    pattern_detection:
      temperature: 0.2
      max_tokens: 300
      
    trend_analysis:
      temperature: 0.3
      max_tokens: 400