primary_model: "anthropic_general_budget"

model_preferences:
  context_summarization:
    primary: "anthropic_general_budget"
    fallback: ["openai_general_budget", "local_general_budget"]
    
  handoff_formatting:
    primary: "anthropic_general_budget"
    fallback: ["openai_general_budget", "local_general_budget"]
    
  complex_context:
    primary: "anthropic_general_standard"
    fallback: ["openai_general_standard", "anthropic_general_budget"]

model_overrides:
  temperature: 0.5
  max_tokens: 1500
  
  per_model:
    claude-3.5-haiku:
      temperature: 0.4
      max_tokens: 1200
      
    claude-3.5-sonnet:
      temperature: 0.6
      max_tokens: 2000