primary_model: "anthropic_general_budget"

model_overrides:
  temperature: 0.4
  max_tokens: 1000
  
  per_model:
    claude-3.5-haiku:
      temperature: 0.3
      max_tokens: 800
      
    claude-3.5-sonnet:
      temperature: 0.5
      max_tokens: 1200