# Application Configuration

# Version information
app_version: "1.0.0"

# Environment (development, staging, production)
environment: "development"

# Application name
app_name: "TEAM ERIC HILT"

# Maintainer contact
maintainer_email: "christopherpmunch@gmail.com"


# Notification settings
notifications:
  email_alerts: not implemented
  slack_alerts: not implemented
  alert_recipients: 
    - "christopherpmunch@gmail.com"


# Default language and locale
default_language: "en-US"

# Time zone for timestamps
timezone: "UTC"