primary_model: "llm_fast_premium"

model_overrides:
  temperature: 0.3
  max_tokens: 1200
  
  # Task-specific overrides
  per_model:
    context_summarization:
      temperature: 0.4
      max_tokens: 1000
      
    relevance_analysis:
      temperature: 0.2
      max_tokens: 600
      
    similarity_detection:
      temperature: 0.1
      max_tokens: 400
      
    recommendation_generation:
      temperature: 0.5
      max_tokens: 800